### PR TITLE
Add GitHub discussions link.

### PR DESCRIPTION
**Pull request by thorwebdev**
## What kind of change does this PR introduce?

- Remove the "Ask a question" issue template.
- Add the "Ask a question" link that kicks out to https://github.com/supabase/supabase/discussions

### CODE REVIEW

**Comment by kiwicopple** [comment]
OK we have some categories now: https://github.com/supabase/supabase/discussions/category_choices

I imagine we want to share these ones?

- Feature requests (Ideas): https://github.com/supabase/supabase/discussions/new?category_id=29638264
- Maybe the Help (?): https://github.com/supabase/supabase/discussions/new?category_id=29638263
- Maybe the Thanks (?) https://github.com/supabase/supabase/discussions/new?category_id=29638266

**Comment by thorwebdev** [comment]
@kiwicopple do you want to move feature requests out of issues? 

I also want to be mindful to not overwhelm with too many choices.

**Comment by kiwicopple** [comment]
Yeah I think feature requests should come out otherwise they sit in the repo forever. It would be nice to just have issues that we're solving in the issues section

**Comment by thorwebdev** [comment]
@kiwicopple Hm, what I don't like about that is that we can't have a template for the discussions. How about we keep feature requests as issues (to have the template) but if it's not something we consider working on immediately we transfer the issue to a discussion. Wdyt?

**Comment by kiwicopple** [comment]
Sounds good to me!

**Pull request merged**
